### ISSUE TITLE
Was this training data set labeled manually? 

### ISSUE THREAD

**Issue by m-ehsani** [ZeerakW/hatespeech#1]
Hi,

I am working on an assignment which involves multiple topics, i.e. racism, profanity, alcohol abuse, etc. Creating positive and negative training data sets for binary classification is very time consuming for each topic. Is there any solution to minimize human intervention to label tweets once creating training data sets?

**Comment by zeeraktalat** [comment]
Hi,

Currently there are none unfortunately and up until now all datasets for hate speech and abuse have been manually annotated. If you have more questions or something you want to discuss, please feel free to e-mail me.

Zeerak
