### ISSUE TITLE
Twitter texts not available through twitter API as they were deleted by twitter

### ISSUE THREAD

**Issue by Sidz204** [ZeerakW/hatespeech#11]
Hi, most of the ids or the tweets were deleted by twitter as they were against their policies. If you have those tweet texts please send or upload them

**Comment by JafarSadikGhub** [comment]
That's also my concern.

**Comment by conorg000** [comment]
Also interested in this. I've found that about 40% of the data is available (I've excluded racist Tweets in my scripting though).

**Comment by katelyn98** [comment]
I just hydrated the IDs today using [these two hydrating methods](https://github.com/echen102/COVID-19-TweetIDs#how-to-hydrate) and only got 62 tweets back. I checked several of the IDs individually and several of the tweets or the accounts have been deleted.

**Comment by zeeraktalat** [comment]
hi @katelyn98 @Sidz204 @JafarSadikGhub @conorg000 you can e-mail me at z.w.butt@sheffield.ac.uk and I can send you the fully hydrated dataset.
