### ISSUE TITLE
Tweets not available through API, some marked as both "racist" and "none"

### ISSUE THREAD

**Issue by Filco306** [ZeerakW/hatespeech#2]
Hello, 

I am currently working on a similar project at university, using your data and paper as a comparison. I have tried to fetch all tweets from `NAACL_SRW_2016.csv` but a lot of tweets, in particular the racist ones, have been removed. Is there perhaps an offline version containing the tweets?

Another problem is that some tweets in the file are marked either both sexism and none or racism and none. These are not many, but does cause issues. An example is id 572340476503724032. Do you have any solution for these? 

Thank you! 

Best,
Filip

**Comment by zeeraktalat** [comment]
Hi Filip,

Yeah I've noticed that too but put it off to fix for a while, I'm not sure where the duplicates come from though as the data the labels are extracted from is unambiguous. If you send me an e-mail I can send you a hydrated version of the dataset.

Z

**Comment by wvs2** [comment]
Hello, I'm student of master program in the Universidade Federal do Pernambuco in Brazil, I'm researching about hate speech detection with sentiment analysis and I'm using  your data and paper as a comparison too. I have the same problem that Filip, you could help me with this?

**Comment by zeeraktalat** [comment]
@wvs2 if you e-mail me I can send you the data. :)

**Comment by Louis-udm** [comment]
The same problem for me. I am a AI student at UdeM, please send the data to me. 
Thanks a lot. @ZeerakW

**Comment by zeeraktalat** [comment]
@Louis-udm I ask you folks to e-mail me because I will forget by the time I have time to send the data. Feel free to e-mail me about it and I'll get it sent to you, otherwise there's a fair chance I'll forget to send it.

**Comment by Louis-udm** [comment]
@ZeerakW I have already sent a request to your paper email.

**Comment by zeeraktalat** [comment]
@Louis-udm if it's the copenhagen university one, then I don't have access to it anymore. Please ping me at z.w.butt@sheffield.ac.uk

**Comment by Louis-udm** [comment]
Yes it is, so I just sent you again to the new e-mail.
