### ISSUE TITLE
Missing Tweets in dataset

### ISSUE THREAD

**Issue by SAN302** [ZeerakW/hatespeech#5]
Hi, I'm doing a research project and I got only a few thousand tweets using twitter API. I think this is because user deleted that tweets or twitter removed them. So, where can I get the file with the downloaded tweets?
Thanks in Advance

**Comment by Gautamshahi** [comment]
Have you resolved the issue? I also wanted to have a original dataset so that I can compare which tweet is deleted

**Comment by zeeraktalat** [comment]
Please see the closed issues on how to get it.
