### ISSUE TITLE
Regarding file NLP+CSS_2016.csv

### ISSUE THREAD

**Issue by vijaykeswani** [ZeerakW/hatespeech#8]
Hey,

Thanks for providing the datasets!
For the file NLP+CSS_2016.csv, opening it using excel or using any default delimiter seems to put most of all labels from "amateur" participants under the first three columns. Were most of the posts labelled by participants represented by these columns, or is there a specific delimiter I need to use to see which participant labelled which post?

Thanks,
Vijay

**Comment by rafaeljjd** [comment]
> Hey,
> 
> Thanks for providing the datasets!
> For the file NLP+CSS_2016.csv, opening it using excel or using any default delimiter seems to put most of all labels from "amateur" participants under the first three columns. Were most of the posts labelled by participants represented by these columns, or is there a specific delimiter I need to use to see which participant labelled which post?
> 
> Thanks,
> Vijay

Hi Vijay, did you ever figure this out? I have the same question

**Comment by vijaykeswani** [comment]
No, I wasn't able to figure out the participant to annotation info.

**Comment by zeeraktalat** [comment]
I'm not entirely sure why that is, perhaps try reading with python csv reader? It was written using that so hopefully that would work.

**Comment by anqiwang365** [comment]
Hi ZeerakW, Thanks for providing the raw data. I have tried to get the data by using tweepy but most of the racist users are suspended. I am doing my graduation project now. Could you help provide the full dataset which contains the tweet content and user relationships? My email is lyul960818@gmail.com. really appreciate your help!!

**Comment by zeeraktalat** [comment]
Hi @anqiwang365 could you e-mail me and I can send you the dataset in an e-mail. My e-mail is z.w.butt@sheffield.ac.uk
