### ISSUE TITLE
Most tweets are not accessible

### ISSUE THREAD

**Issue by mathieulallier807** [ZeerakW/hatespeech#9]
While trying to fetch tweets from both files, this is what I receive as a response for most tweets:

`Twitter Error [200] : [{"errors":[{"value":"551659627872415744","parameter":"ids","resource_type":"tweet","section":"data","title":"Authorization Error","detail":"Sorry, you are not authorized to see the Tweet with ids: [551659627872415744].","type":"https://api.twitter.com/2/problems/not-authorized-for-resource"}]}]`

Is there any other way to get access to the data?

Thanks

**Comment by dwanneruchi** [comment]
Also interested

**Comment by zeeraktalat** [comment]
Please see any of the many closed issues regarding this.
